export const ADDRESS_CARD_THEMES = {
  visited: {
    bgGradient: 'from-rose-50 to-pink-50',
    headerGradient: 'from-rose-500 via-pink-500 to-red-500',
    borderColor: 'border-rose-300',
    accentColor: '#f43f5e',
    primaryButton: 'bg-rose-600 hover:bg-rose-700 text-white shadow-rose-200',
    secondaryButton: 'bg-rose-100 text-rose-700 hover:bg-rose-200 border-rose-200',
    iconColor: 'text-rose-600',
    iconBg: 'bg-rose-100',
    badgeBg: 'bg-rose-100 text-rose-700 border-rose-200',
    titleColor: 'text-rose-800',
    subtitleColor: 'text-rose-600',
    hoverBorder: 'hover:border-rose-400',
    hoverShadow: 'hover:shadow-rose-200/30',
    navButtons: 'bg-rose-50 border-rose-200',
    navDivider: 'bg-rose-300',
    navActive: 'bg-rose-600 text-white hover:bg-rose-700',
    notesBg: 'bg-red-50',
    notesIcon: 'text-red-400',
    notesText: 'text-red-800',
    visitedNavButtons: 'bg-red-50 border-red-200 border shadow-sm',
    visitedNavDivider: 'bg-red-300',
    visitedNavActive: 'bg-red-600 text-white hover:bg-red-700 shadow-sm'
  },
  pending: {
    bgGradient: 'from-emerald-50 to-green-50',
    headerGradient: 'from-emerald-500 via-green-500 to-teal-500',
    borderColor: 'border-emerald-300',
    accentColor: '#10b981',
    primaryButton: 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-200',
    secondaryButton: 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200 border-emerald-200',
    iconColor: 'text-emerald-600',
    iconBg: 'bg-emerald-100',
    badgeBg: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    titleColor: 'text-emerald-800',
    subtitleColor: 'text-emerald-600',
    hoverBorder: 'hover:border-emerald-400',
    hoverShadow: 'hover:shadow-emerald-200/30',
    navButtons: 'bg-emerald-50 border-emerald-200',
    navDivider: 'bg-emerald-300',
    navActive: 'bg-emerald-600 text-white hover:bg-emerald-700',
    notesBg: 'bg-green-50',
    notesIcon: 'text-green-400',
    notesText: 'text-green-800',
    visitedNavButtons: 'bg-emerald-50 border-emerald-200 border shadow-sm',
    visitedNavDivider: 'bg-emerald-300',
    visitedNavActive: 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-sm'
  },
  inProgress: {
    bgGradient: 'from-white to-slate-50',
    headerGradient: 'from-slate-400 via-slate-500 to-slate-600',
    borderColor: 'border-slate-200',
    accentColor: '#64748b',
    primaryButton: 'bg-slate-700 hover:bg-slate-800 text-white shadow-slate-200',
    secondaryButton: 'bg-slate-100 text-slate-700 hover:bg-slate-200 border-slate-200',
    iconColor: 'text-slate-600',
    iconBg: 'bg-slate-100',
    badgeBg: 'bg-slate-100 text-slate-700 border-slate-200',
    titleColor: 'text-slate-800',
    subtitleColor: 'text-slate-600',
    hoverBorder: 'hover:border-slate-300',
    hoverShadow: 'hover:shadow-slate-200/30',
    navButtons: 'bg-slate-100 border-slate-200',
    navDivider: 'bg-slate-300',
    navActive: 'bg-slate-700 text-white hover:bg-slate-800',
    notesBg: 'bg-slate-50',
    notesIcon: 'text-slate-400',
    notesText: 'text-slate-700',
    visitedNavButtons: 'bg-slate-50 border-slate-200 border shadow-sm',
    visitedNavDivider: 'bg-slate-300',
    visitedNavActive: 'bg-slate-700 text-white hover:bg-slate-800 shadow-sm'
  },
  completed: {
    bgGradient: 'from-green-50 to-emerald-100',
    headerGradient: 'from-green-500 via-emerald-500 to-teal-500',
    borderColor: 'border-green-400',
    accentColor: '#16a34a',
    primaryButton: 'bg-green-600 hover:bg-green-700 text-white shadow-green-200',
    secondaryButton: 'bg-green-100 text-green-700 hover:bg-green-200 border-green-200',
    iconColor: 'text-green-600',
    iconBg: 'bg-green-100',
    badgeBg: 'bg-green-100 text-green-700 border-green-300',
    titleColor: 'text-green-800',
    subtitleColor: 'text-green-600',
    hoverBorder: 'hover:border-green-500',
    hoverShadow: 'hover:shadow-green-200/30',
    navButtons: 'bg-green-50 border-green-200',
    navDivider: 'bg-green-300',
    navActive: 'bg-green-600 text-white hover:bg-green-700',
    notesBg: 'bg-green-50',
    notesIcon: 'text-green-500',
    notesText: 'text-green-800',
    visitedNavButtons: 'bg-green-50 border-green-200 border shadow-sm',
    visitedNavDivider: 'bg-green-300',
    visitedNavActive: 'bg-green-600 text-white hover:bg-green-700 shadow-sm'
  }
};

export const getTerritoryAddressTheme = (isVisited) => (
  isVisited ? ADDRESS_CARD_THEMES.visited : ADDRESS_CARD_THEMES.pending
);
