import React from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Bookmark,
  Calendar,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clock,
  Crosshair,
  Database,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Home,
  Info,
  Key,
  Lightbulb,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinOff,
  Navigation,
  Phone,
  Plus,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Star,
  Trash2,
  TrendingUp,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Wifi,
  WifiOff,
  X,
  Zap
} from 'lucide-react';

const ICON_COMPONENTS = {
  activity: Activity,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  bookmark: Bookmark,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  crosshair: Crosshair,
  database: Database,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  filter: Filter,
  flag: Flag,
  home: Home,
  info: Info,
  key: Key,
  lightbulb: Lightbulb,
  loader: Loader2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  map: Map,
  mapOff: MapPinOff,
  mapPin: MapPin,
  navigation: Navigation,
  phone: Phone,
  plus: Plus,
  refresh: RefreshCw,
  refreshCw: RefreshCw,
  save: Save,
  search: Search,
  searchX: SearchX,
  settings: Settings,
  share: Share2,
  shield: Shield,
  smartphone: Smartphone,
  star: Star,
  times: X,
  trash: Trash2,
  'trending-up': TrendingUp,
  unlock: Unlock,
  upload: Upload,
  user: User,
  userPlus: UserPlus,
  users: Users,
  'users-cog': Settings,
  wifi: Wifi,
  wifiOff: WifiOff,
  x: X,
  zap: Zap
};

const Icon = ({ name, size = 24, color = 'currentColor', className = '', ...props }) => {
  const LucideIcon = ICON_COMPONENTS[name];

  if (!LucideIcon) {
    return null;
  }

  return <LucideIcon size={size} color={color} className={className} {...props} />;
};

export default Icon;
